name: "[auto update backend json] merge PR"

on:
  pull_request:
    types:
      - opened
    branches:
      - public-pages

jobs:
  main:
    name    : run main
    runs-on : ubuntu-latest
    if      : startsWith(github.head_ref, 'actions/on-schedule/auto-update-backend-json_')
    timeout-minutes : 60
    steps   :

      - name  : "[STEP] Checkout Repository"
        uses  : actions/checkout@v2

      - name  : "[STEP] Merge PR"
        env   :
          GH_TOKEN     : ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER   : ${{ github.repository_owner }}
          REPO_NAME    : ${{ github.event.repository.name }}
        run   : |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/pull/${PR_NUMBER}"
          gh pr merge ${PR_URL} --merge --delete-branch
